name: Bug report
about: File a but report and help to improve Sanctum
title: "[BUG]"
labels: bug/issue
assignees: jdanielmourao
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Relevant Screenshot(s)
      description: Add screenshots and/or screen recordings to help explain your problem.
    validations:
      required: true
  - type: input
    id: obsi-version
    attributes:
      label: Obsidian Version
      description: You can find the version in the *About* Tab of the Obsidian settings.
      placeholder: "0.15.7"
    validations:
      required: true
  - type: input
    id: installer-version
    attributes:
      label: Installer Version
      description: You can find the installer version in the *About* tab of the Obsidian settings.
      placeholder: "0.14.6"
    validations:
      required: true
  - type: input
    id: font-size
    attributes:
      label: Font Size
      description: You can find your font size setting under the *Appearance* tab of the Obsidian settings.
      placeholder: "16"
    validations:
      required: true
  - type: checkboxes
    id: editor
    attributes:
      label: Which editor are you using?
      description: If you are using the Legacy Editor, please be aware that new features are mostly only supported in the new editor.
      options:
        - label: New Editor
        - label: Legacy Editor
  - type: checkboxes
    id: mode
    attributes:
      label: In which mode(s) does the problem occur? (if applicable)
      options:
        - label: Reading View (Preview)
        - label: Editing View - Source Mode
        - label: Editing View - Live Preview
  - type: checkboxes
    id: operating-system
    attributes:
      label: Which operating system?
      options:
        - label: Windows
        - label: macOS
        - label: Linus
        - label: Android
        - label: iOS
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I updated to the latest version of the theme (Settings → Appearance → Themes - Manage → Update).
          required: true
        - label: I made sure that the issue is related to this theme by checking that the problem does not occur with the default theme.
          required: true
        - label: If the bug occured after updating the theme, I read the last couple [Releases](https://github.com/jdanielmourao/obsidian-sanctum/releases) to make sure the bug is not an intentional change.
          required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
